# Part 1: Visualization

In [1]:
clear
close all
clc

 Install subfolders

In [2]:
addpath tools

 EXERCISE: Frequency response of filters (LECTURE 07, SLIDE 18)
 	write a function calcFreqResponse.m 
 	create FIR and IIR moving average filter coefficients 
 	calculate and visualize frequency response of FIR and IIR filter
 USER SETTINGS 
 
 
 Sampling frequency in Hertz

In [3]:
fs = 16E3;

 Length of moving average FIR filter

In [4]:
L = 5;

In [7]:
FIR_Coeffs = ones(1,L).*1/L


FIR_Coeffs =

    0.2000    0.2000    0.2000    0.2000    0.2000



In [124]:
tau = L*1/fs;
alpha = exp(-1/fs/tau);
IIR_As = [1, -alpha];
IIR_Bs = [1-alpha];

In [130]:
[H_FIR, w_FIR] = calcFreqResponse(FIR_Coeffs, [1], 512);
plot(w_FIR, abs(H_FIR), 'DisplayName', 'FIR Response')
title('Amplitude Responses')
hold on

[H_IIR,w_IIR] = calcFreqResponse(IIR_Bs, IIR_As, 512);

plot(w_IIR,abs(H_IIR), 'DisplayName', 'IIR Response (using Function)')
legend('Location', 'north')

In [132]:
plot(w_FIR, angle(H_FIR), 'DisplayName', 'FIR Phase')
title('Phase Response')
hold on
plot(w_IIR, angle(H_IIR), 'DisplayName', 'FIR Phase')

# Part 2: Biquads

LP/HP

In [266]:
fc = 5000;
k = tan(pi*fc/fs)
q = 1/sqrt(2)
denom = k^2*q+k+q;
lp = [k^2*q 2*k^2*q k^2*q 2*q*(k^2-1) (k^2*q-k+q)]./denom
hp = [q -2*q q 2*q*(k^2-1) k^2*q-k+q]./denom


k =

    1.4966


q =

    0.7071


lp =

    0.4182    0.8363    0.4182    0.4629    0.2097


hp =

    0.1867   -0.3734    0.1867    0.4629    0.2097



In [267]:
[H,w] = calcFreqResponse(lp(1:3), [1 lp(4:end)], 512);
plot(w,H)

BP/BR

In [259]:
f1 = 500;
f2 = 2000;
k = tan(pi*sqrt(f1*f2)/fs)
q = sqrt(f1*f2)/(f2-f1)
denom = k^2*q+k+q;
bp = [k 0 -k 2*q*(k^2-1) k^2*q-k+q]./denom
br = [q*(1+k^2) 2*q*(k^2-1) q*(1+k^2) 2*q*(k^2-1) k^2*q-k+q]./denom


k =

    0.1989


q =

    0.6667


bp =

    0.2230         0   -0.2230   -1.4357    0.5540


br =

    0.7770   -1.4357    0.7770   -1.4357    0.5540



In [269]:
[H_lp,w] = calcFreqResponse(lp(1:3), [1 lp(4:end)], 512);
[H_hp,w] = calcFreqResponse(hp(1:3), [1 hp(4:end)], 512);
[H_bp,w] = calcFreqResponse(bp(1:3), [1 bp(4:end)], 512);
[H_br,w] = calcFreqResponse(br(1:3), [1 br(4:end)], 512);

In [271]:
plot(w,abs(H_lp), 'DisplayName', 'LP')
hold on
plot(w,abs(H_hp), 'DisplayName', 'HP')
plot(w,abs(H_bp), 'DisplayName', 'BP')
plot(w,abs(H_br), 'DisplayName', 'BR')
legend